"""
Test script to verify schematic connections
"""
import requests
import json
import sys
import io

# Set UTF-8 encoding for Windows console
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')

# Test 555 timer netlist
test_netlist = """* 555 Timer LED Blinker Circuit
* Generated by AI Circuit Designer

V1 VCC 0 DC 9.0
U1 1 2 3 4 5 6 7 8 NE555
R1 VCC 7 1.0k
R2 7 6 71.5k
C1 6 0 10.0u
C2 5 0 10n
R3 2 6 0
R4 3 9 1k
D1 9 0 LED
R5 4 VCC 10k
C3 5 0 100n

.tran 10m 1
.end"""

print("Testing schematic connections...")
print("=" * 60)

# Generate schematic
try:
    response = requests.post(
        "http://localhost:8002/eda/schematic",
        json={"netlist": test_netlist},
        timeout=30
    )

    if response.status_code == 200:
        result = response.json()
        if result.get("success"):
            svg = result.get("svg", "")
            summary = result.get("summary", {})

            print("\n✓ Schematic generated successfully!")
            print(f"  Components: {summary.get('total_components', 0)}")
            print(f"  Nets: {summary.get('total_nets', 0)}")

            # Check for connections in SVG
            has_lines = '<line ' in svg or '<polyline ' in svg
            has_nets = 'net' in svg.lower() or 'VCC' in svg or 'GND' in svg

            print(f"\n  Contains connection lines: {has_lines}")
            print(f"  Contains net labels: {has_nets}")

            if has_lines and has_nets:
                print("\n✓ SUCCESS: Schematic has connections!")
            else:
                print("\n✗ FAILED: No connections found!")

            # Save SVG for manual inspection
            with open('test_schematic.svg', 'w', encoding='utf-8') as f:
                f.write(svg)
            print("\n  SVG saved to: test_schematic.svg")
            print("  Open it in a browser to verify connections visually.")

        else:
            print(f"\n✗ Generation failed: {result}")
    else:
        print(f"\n✗ Request failed: {response.status_code}")
        print(f"  Error: {response.text}")

except Exception as e:
    print(f"\n✗ Error: {e}")

print("\n" + "=" * 60)
