"""
SKiDL integration for schematic generation
"""
import logging
import re
from typing import Dict, List, Tuple
import base64
import io

logger = logging.getLogger(__name__)


class SchematicGenerator:
    """Generate circuit schematics using SKiDL"""

    def __init__(self):
        """Initialize schematic generator"""
        try:
            import skidl
            self.skidl = skidl
            logger.info("✓ SKiDL library loaded successfully")
        except ImportError:
            logger.error("✗ SKiDL library not found. Install with: pip install skidl")
            raise

    def parse_spice_netlist(self, netlist: str) -> Dict[str, List[Dict]]:
        """
        Parse SPICE netlist into component and net information

        Args:
            netlist: SPICE netlist string

        Returns:
            Dictionary with components and nets
        """
        components = []
        nets = {}

        lines = netlist.strip().split('\n')

        for line in lines:
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith('*') or line.startswith('.') or line.startswith('+'):
                continue

            # Parse component line
            parts = line.split()
            if len(parts) >= 3:
                comp_name = parts[0]
                nodes = parts[1:-1]  # Nodes between first and last
                value = parts[-1]  # Last part is value/model

                # Determine component type
                comp_type = comp_name[0].upper()

                component = {
                    "name": comp_name,
                    "type": comp_type,
                    "nodes": nodes,
                    "value": value
                }
                components.append(component)

                # Track nets
                for node in nodes:
                    if node not in nets:
                        nets[node] = []
                    nets[node].append(comp_name)

        return {
            "components": components,
            "nets": nets
        }

    def generate_svg_schematic(self, netlist: str) -> str:
        """
        Generate SVG schematic from netlist

        Args:
            netlist: SPICE netlist

        Returns:
            SVG string
        """
        logger.info("Generating SVG schematic")

        try:
            parsed = self.parse_spice_netlist(netlist)
            components = parsed["components"]

            # Create SVG
            svg = self._create_svg_from_components(components)

            logger.info("✓ SVG schematic generated")
            return svg

        except Exception as e:
            logger.error(f"Error generating SVG: {e}")
            # Return simple error SVG
            return self._create_error_svg(str(e))

    def _create_svg_from_components(self, components: List[Dict]) -> str:
        """
        Create SVG from component list

        Args:
            components: List of components

        Returns:
            SVG string
        """
        # Simple grid layout
        svg_width = 800
        svg_height = 600
        grid_size = 100

        svg_parts = []
        svg_parts.append(f'<svg width="{svg_width}" height="{svg_height}" xmlns="http://www.w3.org/2000/svg">')
        svg_parts.append('<!-- Generated by AI Circuit Designer -->')

        # Background
        svg_parts.append(f'<rect width="100%" height="100%" fill="white"/>')

        # Title
        svg_parts.append(f'<text x="400" y="30" text-anchor="middle" font-size="20" font-weight="bold">Circuit Schematic</text>')

        # Draw components
        y_pos = 80
        for i, comp in enumerate(components):
            x_pos = 50 + (i % 7) * grid_size

            # Component symbol
            symbol = self._get_component_symbol(comp["type"])
            color = self._get_component_color(comp["type"])

            # Draw component box
            svg_parts.append(f'<rect x="{x_pos}" y="{y_pos}" width="80" height="60" fill="none" stroke="{color}" stroke-width="2"/>')
            svg_parts.append(f'<text x="{x_pos + 40}" y="{y_pos + 25}" text-anchor="middle" font-size="14" font-weight="bold">{symbol}</text>')
            svg_parts.append(f'<text x="{x_pos + 40}" y="{y_pos + 45}" text-anchor="middle" font-size="12">{comp["name"]}</text>')

            # Move to next row if needed
            if (i + 1) % 7 == 0:
                y_pos += 80

        # Legend
        svg_parts.append('<text x="50" y="550" font-size="12">Legend:</text>')
        svg_parts.append('<rect x="120" y="540" width="15" height="15" fill="none" stroke="green" stroke-width="2"/>')
        svg_parts.append('<text x="140" y="552" font-size="12">Resistor</text>')

        svg_parts.append('<rect x="220" y="540" width="15" height="15" fill="none" stroke="blue" stroke-width="2"/>')
        svg_parts.append('<text x="240" y="552" font-size="12">Capacitor</text>')

        svg_parts.append('</svg>')

        return '\n'.join(svg_parts)

    def _get_component_symbol(self, comp_type: str) -> str:
        """Get symbol for component type"""
        symbols = {
            "R": "R",  # Resistor
            "C": "C",  # Capacitor
            "L": "L",  # Inductor
            "D": "D",  # Diode
            "Q": "Q",  # Transistor
            "U": "IC", # IC
            "V": "V",  # Voltage source
            "I": "I"   # Current source
        }
        return symbols.get(comp_type, "?")

    def _get_component_color(self, comp_type: str) -> str:
        """Get color for component type"""
        colors = {
            "R": "green",   # Resistor
            "C": "blue",    # Capacitor
            "L": "orange",  # Inductor
            "D": "red",     # Diode
            "Q": "purple",  # Transistor
            "U": "black",   # IC
            "V": "brown",   # Voltage source
            "I": "brown"    # Current source
        }
        return colors.get(comp_type, "gray")

    def _create_error_svg(self, error_message: str) -> str:
        """Create error SVG"""
        return f'''<svg width="400" height="200" xmlns="http://www.w3.org/2000/svg">
        <rect width="100%" height="100%" fill="white"/>
        <text x="200" y="80" text-anchor="middle" font-size="16" fill="red">Error Generating Schematic</text>
        <text x="200" y="120" text-anchor="middle" font-size="12">{error_message}</text>
        </svg>'''

    def generate_netlist_summary(self, netlist: str) -> Dict:
        """
        Generate summary of netlist

        Args:
            netlist: SPICE netlist

        Returns:
            Summary dictionary
        """
        parsed = self.parse_spice_netlist(netlist)

        # Count components by type
        component_counts = {}
        for comp in parsed["components"]:
            comp_type = comp["type"]
            component_counts[comp_type] = component_counts.get(comp_type, 0) + 1

        return {
            "total_components": len(parsed["components"]),
            "component_counts": component_counts,
            "total_nets": len(parsed["nets"]),
            "components": parsed["components"]
        }


def generate_schematic(netlist: str) -> Tuple[str, Dict]:
    """
    Generate schematic from netlist

    Args:
        netlist: SPICE netlist

    Returns:
        Tuple of (svg_string, summary_dict)
    """
    generator = SchematicGenerator()
    svg = generator.generate_svg_schematic(netlist)
    summary = generator.generate_netlist_summary(netlist)
    return svg, summary
