"""
Circuit generator - converts parsed requirements to SPICE netlist
"""
import logging
from typing import Dict, List, Any

logger = logging.getLogger(__name__)


class CircuitGenerator:
    """Generate circuit netlists from parsed requirements"""

    def __init__(self):
        """Initialize circuit generator"""
        self.component_counter = {
            "R": 0,  # Resistor
            "C": 0,  # Capacitor
            "L": 0,  # Inductor
            "D": 0,  # Diode
            "Q": 0,  # Transistor
            "U": 0,  # IC
            "V": 0,  # Voltage source
            "I": 0   # Current source
        }

    def reset_counters(self):
        """Reset component counters"""
        for key in self.component_counter:
            self.component_counter[key] = 0

    def get_next_component_id(self, component_type: str) -> str:
        """
        Get next component ID

        Args:
            component_type: Type prefix (R, C, L, etc.)

        Returns:
            Component ID (e.g., R1, C2, etc.)
        """
        if component_type not in self.component_counter:
            self.component_counter[component_type] = 0

        self.component_counter[component_type] += 1
        return f"{component_type}{self.component_counter[component_type]}"

    def generate_555_timer_blinker(self, specs: Dict[str, Any]) -> str:
        """
        Generate 555 timer LED blinker circuit

        Args:
            specs: Circuit specifications

        Returns:
            SPICE netlist
        """
        self.reset_counters()

        # Extract specifications with defaults
        frequency = specs.get("frequency", 1.0)  # Hz
        vcc = specs.get("voltage", 9.0)  # Volts

        # Calculate component values for 555 astable multivibrator
        # f = 1.44 / ((R1 + 2*R2) * C)
        # We'll use C = 10uF, R1 = 1k, calculate R2
        c1 = 10e-6  # 10 microfarad
        r1 = 1000   # 1k ohm
        r2 = (1.44 / (frequency * c1) - r1) / 2

        # Limit R2 to reasonable values
        r2 = max(100, min(r2, 1000000))  # Between 100 and 1M ohm

        netlist = []
        netlist.append("* 555 Timer LED Blinker Circuit")
        netlist.append("* Generated by AI Circuit Designer")
        netlist.append("")

        # Power supply
        v_source = self.get_next_component_id("V")
        netlist.append(f"{v_source} VCC 0 DC {vcc}")

        # 555 Timer connections
        # Pin 1: GND, Pin 2: Trigger, Pin 3: Output
        # Pin 4: Reset, Pin 5: Control, Pin 6: Threshold
        # Pin 7: Discharge, Pin 8: VCC
        u1 = self.get_next_component_id("U")
        netlist.append(f"* 555 Timer (model)")
        netlist.append(f"{u1} 1 2 3 4 5 6 7 8 NE555")

        # Timing components
        r1_resistor = self.get_next_component_id("R")
        r2_resistor = self.get_next_component_id("R")
        c1_capacitor = self.get_next_component_id("C")
        c2_capacitor = self.get_next_component_id("C")

        netlist.append(f"{r1_resistor} VCC 7 {r1/1000}k")
        netlist.append(f"{r2_resistor} 7 6 {r2/1000}k")
        netlist.append(f"{c1_capacitor} 6 0 {c1*1e6}u")
        netlist.append(f"{c2_capacitor} 5 0 10n")

        # Connections
        netlist.append(f"* Connect Trigger (2) to Threshold (6)")
        netlist.append(f"R{self.component_counter['R'] + 1} 2 6 0")

        # LED and current limiting resistor
        r_led = self.get_next_component_id("R")
        led = self.get_next_component_id("D")
        netlist.append(f"{r_led} 3 9 1k")
        netlist.append(f"{led} 9 0 LED")

        # Reset connection
        netlist.append(f"R{self.component_counter['R'] + 1} 4 VCC 10k")

        # Control voltage bypass
        netlist.append(f"C{self.component_counter['C'] + 1} 5 0 100n")

        # Models
        netlist.append("")
        netlist.append(".model NE555 TIMER")
        netlist.append(".model LED D(Is=1e-12 Rs=1 N=1.8 Cjo=10p Vj=0.7)")

        # Simulation commands
        netlist.append("")
        netlist.append(".tran 10m 1")  # Transient analysis: 10ms step, 1s duration
        netlist.append(".end")

        return "\n".join(netlist)

    def generate_opamp_amplifier(self, specs: Dict[str, Any]) -> str:
        """
        Generate op-amp amplifier circuit

        Args:
            specs: Circuit specifications

        Returns:
            SPICE netlist
        """
        self.reset_counters()

        # Extract specifications
        voltage = specs.get("voltage", 15.0)  # Split supply +/- 15V
        gain = specs.get("gain", 10)  # Gain of 10

        # Calculate resistor values
        r_in = 1000  # 1k input resistor
        r_feedback = r_in * gain  # Feedback resistor

        netlist = []
        netlist.append("* Op-Amp Amplifier Circuit")
        netlist.append("* Generated by AI Circuit Designer")
        netlist.append("")

        # Power supplies
        v_pos = self.get_next_component_id("V")
        v_neg = self.get_next_component_id("V")
        netlist.append(f"{v_pos} VCC 0 DC {voltage}")
        netlist.append(f"{v_neg} VEE 0 DC {-voltage}")

        # Op-amp
        u1 = self.get_next_component_id("U")
        netlist.append(f"* Op-Amp (model)")
        netlist.append(f"{u1} 1 2 3 4 5 UA741")

        # Input resistor
        r1 = self.get_next_component_id("R")
        netlist.append(f"{r1} IN 1 {r_in/1000}k")

        # Feedback resistor
        r2 = self.get_next_component_id("R")
        netlist.append(f"{r2} 3 2 {r_feedback/1000}k")

        # Ground reference resistor
        r3 = self.get_next_component_id("R")
        netlist.append(f"{r3} 4 0 {r_in/1000}k")

        # Input and output
        netlist.append("Vin IN 0 AC 1 SIN(0 0.1 1k)")
        netlist.append("* Output is at node 3")

        # Model
        netlist.append("")
        netlist.append(".model UA741 OPAMP(A=200000 ROUT=100)")

        # Simulation
        netlist.append("")
        netlist.append(".ac dec 10 10 100k")
        netlist.append(".tran 10u 10m")
        netlist.append(".end")

        return "\n".join(netlist)

    def generate_led_circuit(self, specs: Dict[str, Any]) -> str:
        """
        Generate simple LED circuit

        Args:
            specs: Circuit specifications

        Returns:
            SPICE netlist
        """
        self.reset_counters()

        voltage = specs.get("voltage", 5.0)

        netlist = []
        netlist.append("* Simple LED Circuit")
        netlist.append("* Generated by AI Circuit Designer")
        netlist.append("")

        # Voltage source
        v1 = self.get_next_component_id("V")
        netlist.append(f"{v1} 1 0 DC {voltage}")

        # Current limiting resistor (assume 20mA LED)
        r1 = self.get_next_component_id("R")
        resistance = (voltage - 2.0) / 0.020  # 2V LED drop
        netlist.append(f"{r1} 1 2 {resistance}")

        # LED
        d1 = self.get_next_component_id("D")
        netlist.append(f"{d1} 2 0 LED")

        # LED model
        netlist.append("")
        netlist.append(".model LED D(Is=1e-12 Rs=1 N=1.8 Cjo=10p Vj=2.0)")

        # Simulation
        netlist.append("")
        netlist.append(".op")  # Operating point analysis
        netlist.append(".end")

        return "\n".join(netlist)

    def generate_netlist(self, requirements: Dict[str, Any]) -> str:
        """
        Generate SPICE netlist from parsed requirements

        Args:
            requirements: Parsed requirements from NLP

        Returns:
            SPICE netlist string
        """
        if requirements.get("schema_version") == "1.0":
            return self.generate_from_ir(requirements)

        topology = requirements.get("topology", {})
        circuit_type = topology.get("type", "unknown")
        specs = requirements.get("specifications", {})

        logger.info(f"Generating netlist for circuit type: {circuit_type}")

        # Route to appropriate generator based on circuit type
        if "555" in str(requirements.get("description", "")).lower() or circuit_type == "timer":
            return self.generate_555_timer_blinker(specs)
        elif circuit_type == "amplifier":
            return self.generate_opamp_amplifier(specs)
        elif "led" in circuit_type or "led" in str(requirements.get("description", "")).lower():
            return self.generate_led_circuit(specs)
        else:
            # Generic circuit - simple LED as fallback
            logger.warning(f"Unknown circuit type: {circuit_type}, using LED circuit")
            return self.generate_led_circuit(specs)

    def generate_from_ir(self, circuit_ir: Dict[str, Any]) -> str:
        """
        Compatibility-only SPICE generation for CircuitIR.

        The main v1 pipeline generates SPICE in the EDA service. This keeps the
        legacy /ai/generate endpoint useful for direct callers.
        """
        circuit_type = circuit_ir.get("circuit_type")
        constraints = circuit_ir.get("constraints", {})

        if circuit_type == "led_current_limiter":
            specs = {
                "voltage": constraints.get("supply_voltage_v", 5.0),
                "current": constraints.get("target_current_a", 0.02),
            }
            return self.generate_led_circuit(specs)

        if circuit_type == "rc_low_pass_filter":
            resistance = constraints.get("resistance_ohm", 10_000.0)
            capacitance = constraints.get("capacitance_f", 15.9e-9)
            return "\n".join([
                "* RC low-pass filter",
                "V1 IN 0 AC 1 SIN(0 1 1000)",
                f"R1 IN OUT {resistance:g}",
                f"C1 OUT 0 {capacitance:g}",
                ".ac dec 20 10 100k",
                ".tran 10u 5m",
                ".end",
            ])

        if circuit_type == "555_timer_blinker":
            return self.generate_555_timer_blinker({
                "voltage": constraints.get("supply_voltage_v", 9.0),
                "frequency": constraints.get("target_frequency_hz", 1.0),
            })

        if circuit_type in {"opamp_inverting", "opamp_non_inverting"}:
            gain = constraints.get("gain", 10.0)
            if circuit_type == "opamp_inverting":
                gain = -abs(gain)
            return "\n".join([
                "* Ideal op-amp amplifier",
                "Vin IN 0 SIN(0 0.1 1000)",
                f"EGAIN OUT 0 IN 0 {gain:g}",
                "RLOAD OUT 0 100k",
                ".tran 10u 5m",
                ".end",
            ])

        raise ValueError(f"Unsupported CircuitIR type: {circuit_type}")


def generate_circuit_design(requirements: Dict[str, Any]) -> str:
    """
    Generate circuit design from requirements

    Args:
        requirements: Parsed requirements

    Returns:
        SPICE netlist
    """
    generator = CircuitGenerator()
    return generator.generate_netlist(requirements)
